Entity/Term.php
<?php

/*
 * This file is part of the kalamu/cms-admin-bundle package.
 *
 * (c) ETIC Services
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Kalamu\CmsAdminBundle\Entity;

use Kalamu\CmsCoreBundle\ContentType\Interfaces\NestableInterface;
use Kalamu\CmsCoreBundle\ContentType\Interfaces\CaracterizableInterface;
use Kalamu\CmsCoreBundle\ContentType\Interfaces\IllustrableInterface;
use Kalamu\CmsCoreBundle\Model\ContentTypeInterface;

use Kalamu\CmsCoreBundle\ContentType\Traits\NestableTrait;
use Kalamu\CmsCoreBundle\ContentType\Traits\CaracterizableTrait;
use Kalamu\CmsCoreBundle\ContentType\Traits\IllustrableTrait;

use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Term
 */
class Term implements ContentTypeInterface, NestableInterface, CaracterizableInterface, IllustrableInterface
{

    use NestableTrait;
    use CaracterizableTrait;
    use IllustrableTrait;

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $libelle;

    /**
     * @var string
     */
    private $slug;

    /**
     * @var string
     */
    private $description;

    /**
     * @var \Kalamu\CmsAdminBundle\Entity\Taxonomy
     */
    private $taxonomy;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
    }


    public function __toString() {
        return sprintf('%s', $this->getLibelle());
    }

    public function validate(ExecutionContextInterface $context){

        if($this->getParent()){
            if($this->getParent()->getTaxonomy() != $this->getTaxonomy()){
                $context->buildViolation("Le term parent ne fait pas parti de la même classification que le term courant")
                        ->atPath('parent')
                        ->addViolation();
            }
        }

    }

    public function getTitle()
    {
        return $this->getLibelle();
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set libelle
     *
     * @param string $libelle
     *
     * @return Term
     */
    public function setLibelle($libelle)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Get libelle
     *
     * @return string
     */
    public function getLibelle()
    {
        return $this->libelle;
    }

    /**
     * Set slug
     *
     * @param string $slug
     *
     * @return Term
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Term
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set taxonomy
     *
     * @param \Kalamu\CmsAdminBundle\Entity\Taxonomy $taxonomy
     *
     * @return Term
     */
    public function setTaxonomy(\Kalamu\CmsAdminBundle\Entity\Taxonomy $taxonomy = null)
    {
        $this->taxonomy = $taxonomy;

        return $this;
    }

    /**
     * Get taxonomy
     *
     * @return \Kalamu\CmsAdminBundle\Entity\Taxonomy
     */
    public function getTaxonomy()
    {
        return $this->taxonomy;
    }
    /**
     * @var string
     */
    private $resume;


    /**
     * Set resume
     *
     * @param string $resume
     *
     * @return Term
     */
    public function setResume($resume)
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * Get resume
     *
     * @return string
     */
    public function getResume()
    {
        return $this->resume;
    }

}

Controller/Admin/SecurityController.php
<?php

namespace Kalamu\CmsAdminBundle\Controller\Admin;

use FOS\UserBundle\Controller\SecurityController as BaseSecurityController;
use FOS\UserBundle\Event\FilterUserResponseEvent;
use FOS\UserBundle\Event\FormEvent;
use FOS\UserBundle\Event\GetResponseUserEvent;
use FOS\UserBundle\FOSUserEvents;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;

/**
 * Controller to manage access to the administration interface
 */
class SecurityController extends BaseSecurityController
{


    /**
     * Renders the login template with the given parameters. Overwrite this function in
     * an extended controller to provide additional data for the login template.
     *
     * @param array $data
     * @return Response
     */
    protected function renderLogin(array $data)
    {
        return $this->container->get('templating')->renderResponse(
            'KalamuCmsAdminBundle:Security:login.html.twig', 
            $data
        );
    }

    public function profileEditAction(Request $request){
        $user= $this->get('security.token_storage')->getToken()->getUser();

        /** @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
        $dispatcher = $this->get('event_dispatcher');
        $event = new GetResponseUserEvent($user, $request);
        $dispatcher->dispatch(FOSUserEvents::PROFILE_EDIT_INITIALIZE, $event);
        if (null !== $event->getResponse()) {
            return $event->getResponse();
        }

        $formFactory = $this->get('fos_user.profile.form.factory');
        $form = $formFactory->createForm()->add('plainPassword', RepeatedType::class, array(
            'type' => PasswordType::class,
            'required' => false,
            'options' => array('translation_domain' => 'FOSUserBundle'),
            'first_options' => array('label' => 'form.password'),
            'second_options' => array('label' => 'form.password_confirmation'),
            'invalid_message' => 'fos_user.password.mismatch',
        ));
        $form->remove('current_password');
        $form->remove('username');
        $form->setData($user);

        $form->handleRequest($request);
        if ($form->isValid()) {
            /** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
            $userManager = $this->get('fos_user.user_manager');
            $event = new FormEvent($form, $request);
            $dispatcher->dispatch(FOSUserEvents::PROFILE_EDIT_SUCCESS, $event);
            $userManager->updateUser($user);
            if (null === $response = $event->getResponse()) {
                $url = $this->generateUrl('fos_user_security_profile');
                $response = new RedirectResponse($url);
            }
            $dispatcher->dispatch(FOSUserEvents::PROFILE_EDIT_COMPLETED, new FilterUserResponseEvent($user, $request, $response));
            return $response;
        }

        return $this->render(
            'KalamuCmsAdminBundle:Security:profile_edit.html.twig', 
            array(
                'form' => $form->createView(), 
                'user'=>$user, 
                'environment' => 'frontend'
            )
        );
    }

    public function profileAction(){
        $user = $this->get('security.token_storage')->getToken()->getUser();
        
        return $this->render(
            'KalamuCmsAdminBundle:Security:profile.html.twig', 
            array(
                'user' => $user, 
                'environment' => 'frontend'
            )
        );
    }

}

Resources/views/Security/login.html.twig
{% extends "SonataAdminBundle::standard_layout.html.twig" %}
{% trans_default_domain 'FOSUserBundle' %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" href="{{asset('/bundles/kalamucmsadmin/css/admin-login.css')}}">
{% endblock %}
{% block sonata_header %}{% endblock %}
{% block sonata_left_side %}{% endblock %}
{% block body_attributes %}class="sonata-bc fixed"{% endblock %}
{% block sonata_page_content -%}
    <div class="form-wrapper">

        <div class="row">
            <div class="col-xs-12">
                {% if error %}
                    <div class="alert alert-danger" role="alert"><strong>{{'Error'|trans({}, 'kalamu')}} : </strong> {{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-3  col-xs-12">
                <a class="logo" href="{{ path('cms_homepage') }}">
                    {% if 'single_text' == sonata_admin.adminPool.getOption('title_mode') or 'both' == sonata_admin.adminPool.getOption('title_mode') %}
                        <img src="{{ asset('bundles/kalamucmsadmin/image/logo.png')}}" alt="{{ sonata_admin.adminPool.title }}">
                    {% endif %}
                </a>
            </div>
            <div class="col-md-8 col-sm-9 col-xs-12">
                <form action="{{ path("fos_user_security_check") }}" method="post" role="form" class="form-inline">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />

                    <div class="form-group">
                        <label class="sr-only" for="inlineFormInputGroup">{{ 'security.login.username'|trans }}</label>
                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                            <div class="input-group-addon"><i class="fa fa-user"></i></div>
                            <input type="text" name="_username" id="username" tabindex="1"  value="{{ last_username }}" required="required" class="form-control" placeholder="{{ 'security.login.username'|trans }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="sr-only" for="inlineFormInputGroup">{{ 'security.login.password'|trans }}</label>
                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                            <div class="input-group-addon"><i class="fa fa-lock"></i></div>
                            <input type="password" name="_password" id="password" tabindex="2" required="required" class="form-control" placeholder="{{ 'security.login.password'|trans }}">
                        </div>
                    </div>

                    <button class="btn-primary btn" name="_submit" tabindex="3" type="submit">{{ 'security.login.submit'|trans }}</button>
                </form>
                <hr>
                <p>
                    <a href="{{path('cms_homepage')}}">
                        {{'Go to homepage'|trans({}, 'kalamu')}}
                    </a>
                </p>
            </div>
        </div>
    </div>
{% endblock sonata_page_content %}


Resources/views/Security/profile.html.twig
{% extends "SonataAdminBundle::standard_layout.html.twig" %}
{% trans_default_domain 'FOSUserBundle' %}

{% block sonata_admin_content %}

    {% block notice %}
        {% include 'SonataCoreBundle:FlashMessage:render.html.twig' %}
    {% endblock notice %}

    <div class="row">
        <div class="col-md-4">
            <div class="box box-primary">
                <div class="box-body box-profile text-center">
                    <i class="fa fa-user-circle-o fa-5x "></i>
                    <h3 class="profile-username text-center">{{ user.username }}</h3>

                  <p class="text-muted text-center">{{ user.email }}</p>

                  <ul class="list-group list-group-unbordered">
                    <li class="list-group-item text-left">
                      <b>{{ 'security.login.username'|trans }}</b> <a class="pull-right">{{user.username}}</a>
                    </li>
                    <li class="list-group-item text-left">
                      <b>{{'Last connection'|trans({}, 'kalamu')}}</b> <a class="pull-right">{{user.lastLogin|format_datetime}}</a>
                    </li>
                    {% if user.superAdmin %}
                    <li class="list-group-item text-left bg-yellow" style="padding-left: 1em">
                        <b><i class="fa fa-star"></i> {{ 'You are super administrator !'|trans({}, 'kalamu') }}</b>
                    </li>
                    {% endif %}
                  </ul>

                  <a href="{{path('fos_user_security_profile_edit')}}" class="btn btn-primary btn-block"><b>{{ 'Edit my profile'|trans({}, 'kalamu') }}</b></a>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header">
                    <h4 class="box-title">
                        {{ 'Access groups'|trans({}, 'kalamu') }}
                    </h4>
                </div>
                <div class="box-body box-profile text-center">
                  <ul class="list-group list-group-unbordered">
                    {% for group in user.groups %}
                        <li class="list-group-item text-left">
                          <b><i class="fa fa-group"></i> {{group}}</b>
                        </li>
                    {% else %}
                        <li class="list-group-item text-center">
                            <em>{{ 'Your are in no group'|trans({}, 'kalamu') }}</em>
                        </li>
                    {% endfor %}
                  </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock sonata_admin_content %}

Resources/views/Security/profile_edit.html.twig
{% extends "SonataAdminBundle::standard_layout.html.twig" %}
{% trans_default_domain 'FOSUserBundle' %}


{% block sonata_admin_content %}
    {% trans_default_domain 'FOSUserBundle' %}

    {% block notice %}
        {% include 'SonataCoreBundle:FlashMessage:render.html.twig' %}
    {% endblock notice %}

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="col-md-2">
                        <div class="box-profile text-center" style="margin-top:2em">
                            <i class="fa fa-user-circle-o fa-5x "></i>
                            <h3 class="profile-username text-center">{{ user.username }}</h3>
                            <p class="text-muted text-center">{{ user.email }}</p>
                        </div>
                    </div>

                    <div class="col-md-10">

                        <h4 class="box-title ">
                            {{ 'Edit my profile'|trans({}, 'kalamu') }}
                        </h4>

                        {{ form_start(form) }}

                            <div class="row">
                                <div class="col-md-8">
                                    {{ form_row(form.email) }}
                                    {{ form_row(form.plainPassword) }}
                                </div>
                                <div class="col-md-4">
                                    <div id="passwordInfo" style="display: none;">
                                        <h4>{{ 'Password strength'|trans({}, 'kalamu') }} : <strong></strong></h4>

                                        <div class="progress">
                                            <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            </div>
                                        </div>

                                        <p>
                                            {{ "password_strength_help"|trans({}, 'kalamu') }}
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> {{ "Save"|trans({}, 'kalamu') }}</button>
                                <a href="{{path('fos_user_security_profile')}}" class="btn btn-default"><i class="fa fa-times"></i> {{ "Cancel"|trans({}, 'kalamu') }}</a>
                            </div>
                            {{ form_rest(form) }}
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock sonata_admin_content %}


{% block javascripts_footer %}
    <script src="{{asset('bundles/kalamucmsadmin/js/passwordStrengthMeter.js')}}"></script>
    <script>
    $(function(){
        var passwordStrengthMeter = {
            'Trop faible':  {class: 'danger', progress: 'red', nbBlock: 1},
            'Faible':       {class: 'danger', progress: 'red', nbBlock: 2},
            'Moyen':        {class: 'warning', progress: 'yellow', nbBlock: 3},
            'Fort':         {class: 'success', progress: 'green', nbBlock: 4}
        };

        $('#{{form.plainPassword.first.vars.id}}').on('change keyup', function(){
            var passwordStrength = Math.min(100, checkPasswordStrength($(this).val()));
            console.log('Force :'+passwordStrength);
            var strength;
            if(passwordStrength <= 40){
                strength = 'Trop faible';
            }else if(passwordStrength <= 50){
                strength = 'Faible';
            }else if(passwordStrength <= 60){
                strength = 'Moyen';
            }else{
                strength = 'Fort';
            }

            if($(this).val().length > 0){
                $('#passwordInfo').show();
                $('#passwordInfo h4 strong').attr('class', 'text-'+passwordStrengthMeter[strength].class).text(strength);

                $('#passwordInfo .progress-bar').attr('class', 'progress-bar progress-bar-'+passwordStrengthMeter[strength].progress)
                        .attr('aria-valuenow', passwordStrength)
                        .css('width', passwordStrength+'%');
            }else{
                $('#passwordInfo').hide();
            }
        });
    });
</script>
{% endblock %}